### ISSUE TITLE
Default tmux layout to 'tiled'

### ISSUE THREAD

**Issue by hardfalcon** [hukl/toolbox#17]
Hi, would it be possible to default the tmux layout to 'tiled' instead of 'even-vertical'?

At least with tmux 1.8 (CentOS, don't ask), tmux seems to more or less blow up once it doesn't have enough "screen estate" to actually draw the single panes.

With the default 'even-vertical' layout, things already blow up with only two dozen nodes, whilst with 'tiled' I can easily handle something in the ballpark of 175 nodes (175 nodes work, 200 nodes don't - but that's probably only my small laptop display, and I could well imagine that more nodes are possible with my dual screen setup at the office).

**Comment by hardfalcon** [comment]
Nevermind, this seems to be a bug in tmux 1.8. Using tmux 2.5, I can do over 300 nodes simultanously without any problem whatsoever.

**Comment by hardfalcon** [comment]
I've just tried with tmux 2.5, and I could successfully do more than 300 nodes simultaneously without any problems. However this only worked with the 'tiled' layout - when using the default layout, memory and CPU usage go through the roof and tmux essentially crashes.

**Comment by hukl** [comment]
Hmm that is indeed interesting but you can specify the layout with a command line flag. I don't want to change the default. Maybe in the future there will be even a config file if enough users ask for it :)
