### ISSUE TITLE
pane-base-index other than 0

### ISSUE THREAD

**Issue by tibra** [hukl/toolbox#4]
Hi hukl,

I was wondering why hostmux would ignore my first option in the host list, ie. `hostmux user@host1 user@host2 user@host3` opens three panes but only connects to host2 and host3 and ignores host1, leaving it in an empty pane. After experimenting with my .tmux.conf, I've found that my `pane-base-index` was set to 1 rather than 0 because I like to count human-style from 1..n when addressing panes and tabs.

There might be a way to set your `PANE_INDEX=0` to the `pane-base-index` from `.tmux.conf`. Can you access settings from the tmux config in hostmux?

Thanks, hostmux is much appreciated here :-)

**Comment by hukl** [comment]
not sure if I can read that setting from tmux directly - that would be the best option. maybe you can investigate that? :)

**Comment by hukl** [comment]
another option could be that I explicitly set it for that session and provide an option to override it

**Comment by hukl** [comment]
this should at least make it work but it won't be your preference

https://github.com/hukl/hostmux/commit/fd5c5fc26e14f513488a6b81ea9d927f686190b3

**Comment by hukl** [comment]
this should be the dynamic version - please test: https://github.com/hukl/hostmux/tree/pane_index

**Comment by tibra** [comment]
Wonderful, works perfectly 😊
`tmux show-window-options` is pretty neat! Thank you!
